# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 최다정 Dajeong Choe
title: Back-end Web Developer
email: hers010801@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  allrightDJ0108
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: dajeong-choe-최다정-902bb829b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: da-zzling.tistory.com
    icon: fas fa-globe
    url: https://da-zzling.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. **경험하고 공감하는 개발자** 최다정입니다.
  
  발전해가는 많은 기술을 다양한 사람들이 유용하게 사용하는 세상을 만들고자 개발자를 꿈꾸게 되었습니다.
  
  공감하는 Back-end 개발자로서, 항상 사용자의 입장에서 생각하고 그들의 편의를 위한 기술을 만들기 위해 노력하겠습니다.
  
  웹 서비스 개발 회사에서 Back-End, Front-End의 역할을 모두 담당하는 웹 개발자로 근무한 경험이 있습니다.
  
  이 경험을 바탕으로 JAVA를 이용한 개발 능력과 Linux 서버 및 Oracle, MySQL 등 다양한 DB 개발 능력을 기를 수 있었습니다.
  
  또한, 커뮤니케이션을 좋아하여 상대방의 의도를 신속히 파악하고, 제 의견을 조리 있게 주장하는 것에 자신이 있습니다.
  

content:

  - title: Project # 프로젝트
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: DalKom.Shop
        link:
        sub_title: PM <br> Backend Developer <br> Monitoring
        caption: 2024년 01월 - 2024년 02월 (2개월)
        description: | # this will include new lines to allow paragraphs
          기업주도 집중프로젝트 교육 프로그램에서 임직원 전용 쇼핑몰
          KEA SW Academy에서 진행한 기업실무 프로젝트에서 임직원 전용 쇼핑몰인 DalKom.Shop 프로젝트에 참여했습니다. <br>
          10명으로 구성된 팀의 PM을 맡았으며, 
          
          [ 개발 ]
          - 시스템과 Jira 연동
          - 관리자 통계 서비스 및 전용 대시보드 개발
          - Elasticsearch를 활용한 유사어 검색 개발
          - Elastic Stack을 활용한 모니터링 담당
          
          [ 기술 스택 ]
          - <mark>Java</mark>, <mark>React</mark>, <mark>Spring Boot</mark>, <mark>Gradle</mark>
          - <mark>AWS</mark>, <mark>KaKao Cloud</mark>, <mark>Elastic Stack</mark>
          - <mark>Docker</mark>, <mark>GitHub Actions</mark>, <mark>Sonarqube</mark>, <mark>JUnit5</mark>, <mark>K6</mark>
          - <mark>JPA</mark>, <mark>MyBatis</mark>, <mark>MySQL</mark>, <mark>Elasticsearch</mark>
          - <mark>GitHub</mark>, <mark>Jira</mark>, <mark>Slack</mark>, <mark>Notion</mark>, <mark>intellij</mark>, <mark>DBeaver</mark>
      

      - title: Allways Blog
        link:
        sub_title: Backend Developer <br> Monitoring
        caption: 2022년 09월 - 2022년 12월 (4개월)
        description: | # this will include new lines to allow paragraphs
          KEA SW Academy에서 블로그 웹 서비스를 주제로 PBL 프로젝트를 진행했습니다. <br>
          생성형 AI 기술을 활용한 사용자 친화적 블로그를 개발했으며, 그 중 아래 항목을 담당했습니다. <br><br>
          
          [ 역할 ]
          - BackEnd Developer
          - Monitoring
          
          [ 개발 ]
          - 시스템과 Jira 연동
          - 관리자 통계 서비스 및 전용 대시보드 개발
          - Elasticsearch를 활용한 유사어 검색 개발
          - Elastic Stack을 활용한 모니터링 담당
          
          [ 기술 스택 ]
          - <mark>Java</mark>, <mark>Python</mark>, <mark>React</mark>, <mark>Spring Boot</mark>, <mark>Fast API</mark>, <mark>Gradle</mark>
          - <mark>AWS</mark>, <mark>Elastic Stack</mark>
          - <mark>Docker</mark>, <mark>Jenkins</mark>, <mark>Sonarqube</mark>, <mark>JUnit5</mark>, <mark>JMeter</mark>
          - <mark>JPA</mark>, <mark>MySQL</mark>, <mark>MongoDB</mark>, <mark>Kafka</mark>, <mark>Debezium</mark>, <mark>Confluent</mark>
          - <mark>GitHub</mark>, <mark>Jira</mark>, <mark>Slack</mark>, <mark>Notion</mark>, <mark>intellij</mark>, <mark>DBeaver</mark>
          

  - title: Certificate # 수료증
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Terraform - Multi Cloud Orchestration
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 파이브웍스
        caption: 2023년 12월
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <strong>멀티클라우드 환경의 오케스트레이션 실전구현</strong> <br>
          멀티클라우드 현황 교육, Terraform을 활용한 멀티클라우드 환경 구축 실습

      - title: Elastic for DevOps <br>Monitoring and Testing Implementation
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 로이드케이
        caption: 2023년 11월
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          <strong>데브옵스 환경의 모니터링과 테스트 실전구현</strong> <br>
          Elastic을 활용한 기초 교육, Kibana, Rules & Connectors, Observability 솔루션 실습을 진행했습니다. <br>
          30명의 학생 중 5명을 선발하는 교육우수생으로 선발되어 Elastic 자격증 취득 교육을 받았습니다.

      - title: AWS JAM
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: AWS (Amazon Web Services)
        caption: 2023년 11월
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          실제 AWS 서비스 사용 사례에 대한 문제를 해결하여 실시간으로 점수를 획득하는 AWS JAM 이벤트에 참여했습니다.
          AWS 서비스에 대한 이해도를 바탕으로 총 30명의 참가자 중에서 1위를 달성하였습니다.

  - title: License # 자격증
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: AWS SAA
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: AWS (Amazon Web Services)
        caption: 2024년 01월
        # quote: >
        description: | # this will include new lines to allow paragraphs
          <strong>AWS Certified Solutions Architect Associate</strong> <br>
          AWS (Amazon Web Services) <br>
          AWS04123722

      - title: SQLD
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: 한국데이터산업진흥원
        caption: 2023년 10월
        # quote: >
        description: | # this will include new lines to allow paragraphs
          <strong>SQL Developer</strong> <br>
          한국데이터산업진흥원 <br>
          SQLD-050009906

      - title: 정보처리기사
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: 한국산업인력공단
        caption: 2023년 07월
        # quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          한국산업인력공단 <br>
          23201100830V



  - title: Activity # 활동
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 모각코 스터디
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: 가천 카카오엔터프라이즈 SW Academy 3기
        caption: 2023년 02월 - 진행중
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          이 활동을 통해 다양한 프로젝트 경험, 팀원과의 협업 능력을 향상 시킬 수 있었습니다.  <br>
          
          기술 스택
            - <mark>MSA</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>DevOps</mark>, <mark>CI/CD</mark>, <mark>Terraform</mark>, <mark>AWS</mark>, <mark>KaKao Cloud</mark>

      - title: 가천 카카오엔터프라이즈 <br>SW Academy
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: KEA SW Academy 3기
        caption: 2023년 09월 - 2024년 02월 (6개월)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          ~고, 프로젝트 경험을 늘리고자 Academy 활동을 시작하게 되었습니다.
          이 활동을 통해 각종 IT 세미나는 물론 다양한 프로젝트 경험, 팀원과의 협업 능력을 향상 시킬 수 있었습니다. <br>

          기술 스택
            - <mark>MSA</mark>, <mark>Kubernetes</mark>, <mark>Docker</mark>, <mark>DevOps</mark>, <mark>CI/CD</mark>, <mark>Terraform</mark>, <mark>AWS</mark>, <mark>KaKao Cloud</mark>

      - title: LET Speech Club
        link: https://www.instagram.com/letspeechclub/
        sub_title: 대학 연합 발표동아리 22기 <br> 홍보부장
        caption: 2018년 01월 - 2019년 01월 (1년)
        description: | # this will include new lines to allow paragraphs
          ~기 위해 매주 다른 주제로 발표하는 대학 연합 발표 동아리에서 활동했습니다. <br>
          이 활동을 통해 소통 능력, 발표 경험을 향상 시킬 수 있었습니다. <br>
          
          기술 스택
            - <mark>Communication</mark>, <mark>Presentaion</mark>

  - title: Experience # 경력사항
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 싸이웍스
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Web Developer
        caption: 2021년 08월 - 2023년 06월 (1년 11개월)
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          웹 서비스 개발 회사에서 대학별 개인역량관리 시스템 및 현장실습시스템 프로젝트 사업에 참여했습니다. <br>
          Web Developer로 근무하면서 기획자와 소통하며 고객에게 최선의 서비스를 제공했습니다.

  - title: Education # 학력
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Gachon University
        caption: 2017년 - 2023년
        sub_title: 가천대학교
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          컴퓨터공학 학사 Computer Engineering <br>
          평점 3.93 / 4.5



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
